name: sports-research-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - openai
      - python-dotenv
      - pydantic
      - fastapi
      - langtrace-python-sdk
      - requests
      - ipykernel
