name: sports-research-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - openai>=1.0.0
      - python-dotenv
      - pydantic
      - fastapi
      - langfuse
      - requests
      - ipykernel
