name: sports-research-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - openai==1.14.0
      - python-dotenv==1.0.1
      - pydantic==2.6.4
      - fastapi==0.110.0
      - uvicorn==0.27.1
      - python-multipart==0.0.9
